"""Display labels for Tiếng Anh 9 ontology (keeps English grammar names + Vietnamese glosses)."""

DISPLAY_LABELS = {
    # Grammar structures
    'GR_PresentSimple': 'Thì hiện tại đơn (Present Simple)',
    'GR_PresentContinuous': 'Thì hiện tại tiếp diễn (Present Continuous)',
    'GR_PresentPerfect': 'Thì hiện tại hoàn thành (Present Perfect)',
    'GR_PresentPerfectContinuous': 'Thì hiện tại hoàn thành tiếp diễn (Present Perfect Continuous)',
    'GR_PastSimple': 'Thì quá khứ đơn (Past Simple)',
    'GR_PastContinuous': 'Thì quá khứ tiếp diễn (Past Continuous)',
    'GR_PastPerfect': 'Thì quá khứ hoàn thành (Past Perfect)',
    'GR_FutureSimple': 'Thì tương lai đơn (Future Simple — will/shall)',
    'GR_FutureGoingTo': 'Tương lai gần (be going to)',
    'GR_Modals': 'Động từ khuyết thiếu (can/could/should/must/may)',
    'GR_Passive': 'Câu bị động (Passive voice)',
    'GR_Passive_Tenses': 'Bị động ở các thì khác nhau',
    'GR_Cond_0': 'Câu điều kiện loại 0 (Zero conditional)',
    'GR_Cond_1': 'Câu điều kiện loại 1 (First conditional)',
    'GR_Cond_2': 'Câu điều kiện loại 2 (Second conditional)',
    'GR_Cond_3': 'Câu điều kiện loại 3 (Third conditional)',
    'GR_Reported': 'Câu tường thuật (Reported speech)',
    'GR_Relative_Defining': 'Mệnh đề quan hệ xác định (who/which/that)',
    'GR_Relative_NonDef': 'Mệnh đề quan hệ không xác định (có dấu phẩy)',
    'GR_Wishes': 'Câu ước (I wish / If only)',
    'GR_PhrasalVerbs': 'Cụm động từ (phrasal verbs)',
    'GR_Gerund_Inf': 'Danh động từ và động từ nguyên mẫu (V-ing vs to-V)',
    'GR_Comparisons': 'So sánh hơn và so sánh nhất',
    'GR_ComparisonAs': 'So sánh bằng (as…as)',
    'GR_Articles': 'Mạo từ (a/an/the)',
    'GR_Prepositions': 'Giới từ (chỉ thời gian, nơi chốn, hướng)',
    'GR_Connectors': 'Từ nối cơ bản (and/but/so/because/although)',
    'GR_Connectors_Adv': 'Từ nối nâng cao (however, nevertheless, despite, in spite of)',
    'GR_Tag': 'Câu hỏi đuôi (Tag questions)',

    # Vocabulary topics
    'V_LocalEnvironment': 'Môi trường địa phương (làng nghề, truyền thống)',
    'V_CityLife': 'Cuộc sống thành thị',
    'V_TeenLife': 'Đời sống tuổi teen / vị thành niên',
    'V_LearningLanguages': 'Học một ngoại ngữ',
    'V_VNWonders': 'Các kỳ quan Việt Nam / thế giới',
    'V_VNThenAndNow': 'Việt Nam xưa và nay',
    'V_Food_Recipes': 'Công thức nấu ăn và thói quen ăn uống',
    'V_Tourism': 'Du lịch',
    'V_EnglishInTheWorld': 'Tiếng Anh trên thế giới',
    'V_SpaceTravel': 'Du hành vũ trụ / khám phá không gian',
    'V_ChangingRoles': 'Vai trò thay đổi trong xã hội (giới, công việc)',
    'V_MyFutureCareer': 'Nghề nghiệp tương lai',
    'V_Environment': 'Môi trường và ô nhiễm',
    'V_Education': 'Giáo dục',
    'V_Technology': 'Công nghệ / máy tính / truyền thông',
    'V_Health': 'Sức khỏe và bệnh tật',
    'V_Entertainment': 'Giải trí (phim, âm nhạc)',
    'V_CulturesCountries': 'Văn hóa và các quốc gia',

    # Language functions
    'LF_Describing': 'Miêu tả (người, nơi chốn, đồ vật)',
    'LF_Comparing': 'So sánh, đối chiếu',
    'LF_GivingOpinion': 'Nêu và bảo vệ ý kiến',
    'LF_AgreeDisagree': 'Đồng ý và không đồng ý',
    'LF_Suggesting': 'Đề xuất / gợi ý',
    'LF_Requesting': 'Yêu cầu, đề nghị',
    'LF_GivingAdvice': 'Đưa ra lời khuyên',
    'LF_TalkingAboutPast': 'Nói về trải nghiệm / sự kiện quá khứ',
    'LF_TalkingAboutFuture': 'Nói về kế hoạch / dự đoán tương lai',
    'LF_HypotheticalThinking': 'Giả định (nếu…)',
    'LF_Narrating': 'Kể chuyện / tường thuật chuỗi sự kiện',
    'LF_Persuading': 'Thuyết phục',

    # Skills
    'SK_Reading': 'Đọc hiểu',
    'SK_Listening': 'Nghe hiểu',
    'SK_Writing': 'Viết',
    'SK_Speaking': 'Nói',
    'SK_GrammarVocabUse': 'Sử dụng ngữ pháp và từ vựng (Use of English)',

    # Text types
    'TT_FormalLetter': 'Thư / email trang trọng',
    'TT_InformalLetter': 'Thư / email thân mật',
    'TT_Narrative': 'Văn tự sự (kể chuyện)',
    'TT_Descriptive': 'Văn miêu tả (người / nơi)',
    'TT_OpinionEssay': 'Bài luận nêu ý kiến (opinion essay)',
    'TT_ForAgainstEssay': 'Bài luận hai mặt (for-and-against essay)',
    'TT_Report': 'Báo cáo (report)',
    'TT_Article': 'Bài báo / bài viết (article)',
    'TT_Dialogue': 'Đối thoại / hội thoại',
    'TT_Announcement': 'Thông báo',
}
