"""Display labels with Vietnamese diacritics for Ngữ Văn 9 ontology."""

DISPLAY_LABELS = {
    # Historical periods
    'HP_TrungDai': 'Văn học trung đại Việt Nam (thế kỷ X–XIX)',
    'HP_CanDai': 'Văn học cận đại (cuối XIX – đầu XX)',
    'HP_1930_1945': 'Văn học 1930–1945 (Thơ Mới, văn hiện thực)',
    'HP_KhangChien': 'Văn học kháng chiến chống Pháp và Mỹ (1945–1975)',
    'HP_HienDai': 'Văn học Việt Nam hiện đại (sau 1975)',
    'HP_NuocNgoai': 'Văn học nước ngoài',

    # Genres
    'G_TruyenTho': 'Truyện thơ (chữ Nôm)',
    'G_TruyenNgan': 'Truyện ngắn',
    'G_TieuThuyet': 'Tiểu thuyết',
    'G_ThoLucBat': 'Thơ lục bát',
    'G_ThoBayChuTuDo': 'Thơ bảy chữ / thơ tự do',
    'G_ThoTruTinh': 'Thơ trữ tình hiện đại',
    'G_Kich': 'Kịch nói',
    'G_VanNghiLuan': 'Văn nghị luận (xã hội, văn học)',
    'G_BuoiKy_TuyBut': 'Bút ký, tùy bút',
    'G_TruyenCo': 'Truyện cổ (nước ngoài)',

    # Authors
    'A_NguyenDu': 'Nguyễn Du (Thanh Hiên)',
    'A_NguyenDinhChieu': 'Nguyễn Đình Chiểu (Đồ Chiểu)',
    'A_NguyenDu_Cu': 'Nguyễn Dữ (thế kỷ XVI — tác giả Truyền Kỳ Mạn Lục) [GHI CHÚ: trong ontology đang bị nhầm với Nguyễn Du]',
    'A_NguyenDu_NamXuong': 'Nguyễn Dữ (tác giả Truyền Kỳ Mạn Lục)',
    'A_NgoGiaVanPhai': 'Ngô gia văn phái',
    'A_ChinhHuu': 'Chính Hữu',
    'A_PhamTienDuat': 'Phạm Tiến Duật',
    'A_NguyenDuy': 'Nguyễn Duy',
    'A_BangViet': 'Bằng Việt',
    'A_NguyenKhoaDiem': 'Nguyễn Khoa Điềm',
    'A_HuyCan': 'Huy Cận',
    'A_HuuThinh': 'Hữu Thỉnh',
    'A_ThanhHai': 'Thanh Hải',
    'A_VienPhuong': 'Viễn Phương',
    'A_YPhuong': 'Y Phương',
    'A_CheLanVien': 'Chế Lan Viên',
    'A_KimLan': 'Kim Lân',
    'A_NguyenThanhLong': 'Nguyễn Thành Long',
    'A_NguyenQuangSang': 'Nguyễn Quang Sáng',
    'A_NguyenMinhChau': 'Nguyễn Minh Châu',
    'A_LeMinhKhue': 'Lê Minh Khuê',
    'A_NguyenHuyTuong': 'Nguyễn Huy Tưởng',
    'A_LuuQuangVu': 'Lưu Quang Vũ',
    'A_Maupassant': 'Guy de Maupassant (Mô-pa-xăng)',
    'A_Gorki': 'Maxim Gorki (Mác-xim Go-rơ-ki)',
    'A_DanielDefoe': 'Daniel Defoe (Đi-phô)',
    'A_LaPhongTen': 'Jean de La Fontaine (La Phông-ten)',

    # Works
    'W_TruyenKieu': 'Truyện Kiều (Đoạn trường tân thanh)',
    'W_ChuyenNguoiConGaiNX': 'Chuyện người con gái Nam Xương',
    'W_HoangLeNhatThongChi_14': 'Hoàng Lê nhất thống chí – Hồi thứ 14',
    'W_LucVanTien_CuuKNN': 'Lục Vân Tiên cứu Kiều Nguyệt Nga (trích)',
    'W_DongChi': 'Đồng chí',
    'W_BaiThoTDXKK': 'Bài thơ về tiểu đội xe không kính',
    'W_AnhTrang': 'Ánh trăng',
    'W_BepLua': 'Bếp lửa',
    'W_KhucHatRu': 'Khúc hát ru những em bé lớn trên lưng mẹ',
    'W_DoanThuyenDanhCa': 'Đoàn thuyền đánh cá',
    'W_SangThu': 'Sang thu',
    'W_MuaXuanNhoNho': 'Mùa xuân nho nhỏ',
    'W_ViengLangBac': 'Viếng lăng Bác',
    'W_NoiVoiCon': 'Nói với con',
    'W_ConCo': 'Con cò',
    'W_Lang': 'Làng',
    'W_LangLeSaPa': 'Lặng lẽ Sa Pa',
    'W_ChiecLuocNga': 'Chiếc lược ngà',
    'W_BenQue': 'Bến quê',
    'W_NhungNgoiSao_XX': 'Những ngôi sao xa xôi',
    'W_BacSon': 'Bắc Sơn (trích)',
    'W_ToiVaChungTa': 'Tôi và chúng ta (trích)',
    'W_BoCuaXiMong': 'Bố của Xi-mông',
    'W_NhungDuaTreGorki': 'Những đứa trẻ (trích "Thời thơ ấu")',
    'W_RobinsonCruxo': 'Rô-bin-xơn Cru-xô (trích)',
    'W_ChoSoiVaCuu_LPT': 'Chó sói và cừu trong thơ ngụ ngôn của La Phông-ten',

    # Characters
    'CH_ThuyKieu': 'Thúy Kiều',
    'CH_ThuyVan': 'Thúy Vân',
    'CH_KimTrong': 'Kim Trọng',
    'CH_MaGiamSinh': 'Mã Giám Sinh',
    'CH_TuHai': 'Từ Hải',
    'CH_HoanThu': 'Hoạn Thư',
    'CH_VuNuong': 'Vũ Nương (Vũ Thị Thiết)',
    'CH_TruongSinh': 'Trương Sinh',
    'CH_LucVanTien': 'Lục Vân Tiên',
    'CH_KieuNguyetNga': 'Kiều Nguyệt Nga',
    'CH_NguoiLinh_DC': 'Anh lính (trong "Đồng chí")',
    'CH_NguoiLai_TDXKK': 'Người lái xe Trường Sơn',
    'CH_OngHai': 'Ông Hai',
    'CH_AnhThanhNien': 'Anh thanh niên (làm khí tượng)',
    'CH_OngSau': 'Ông Sáu (cha bé Thu)',
    'CH_BeThu': 'Bé Thu',
    'CH_NhiBenQue': 'Nhĩ (Bến quê)',
    'CH_PhuongDinh': 'Phương Định (Những ngôi sao xa xôi)',
    'CH_Thao': 'Thao (Những ngôi sao xa xôi)',
    'CH_NhoNgoiSao': 'Nho (Những ngôi sao xa xôi)',
    'CH_XiMong': 'Xi-mông',
    'CH_PhiLip': 'Bác Phi-líp',

    # Literary devices
    'LD_SoSanh': 'So sánh (biện pháp tu từ)',
    'LD_NhanHoa': 'Nhân hóa',
    'LD_AnDu': 'Ẩn dụ',
    'LD_HoanDu': 'Hoán dụ',
    'LD_DiepNgu': 'Điệp ngữ',
    'LD_DiepCauTruc': 'Điệp cấu trúc',
    'LD_DaoNgu': 'Đảo ngữ (đảo trật tự cú pháp)',
    'LD_LietKe': 'Liệt kê',
    'LD_DoiLap': 'Tương phản / đối lập',
    'LD_CauHoiTuTu': 'Câu hỏi tu từ',
    'LD_NoiQuaQuaPhong': 'Nói quá, cường điệu (phóng đại)',
    'LD_NoiGiamNoiTranh': 'Nói giảm, nói tránh',
    'LD_Choi_Chu': 'Chơi chữ',
    'LD_DienCo': 'Điển cố, điển tích',
    'LD_TuongTrung': 'Tượng trưng / biểu tượng',
    'LD_TruongTu_Vong': 'Trường từ vựng',
    'LD_TuLay': 'Từ láy (gợi cảm giác)',
    'LD_TuTuongHinh': 'Từ tượng hình, từ tượng thanh',

    # Themes
    'T_TinhYeuQueHuong': 'Tình yêu quê hương, đất nước',
    'T_TinhDongChi': 'Tình đồng chí, đồng đội',
    'T_TinhCamGiaDinh': 'Tình cảm gia đình (mẹ con, cha con, bà cháu)',
    'T_ThanPhanPhuNu': 'Thân phận người phụ nữ phong kiến',
    'T_VeDepNguoiLaoDong': 'Vẻ đẹp người lao động',
    'T_VeDepNguoiLinh': 'Vẻ đẹp người lính cách mạng',
    'T_LongYeuNuoc': 'Lòng yêu nước',
    'T_KhaoVongHoaBinh': 'Khao vọng hòa bình, cuộc sống yên ấm',
    'T_CaiThienSungSuc': 'Cái thiện và cái ác; công lý',
    'T_SuCoDon_TrietLy': 'Sự cô đơn, triết lý nhân sinh',
    'T_Bien_VoTan': 'Thiên nhiên – biển cả, vũ trụ',
    'T_SuChuyenGiao': 'Sự chuyển giao thế hệ, truyền thống',
    'T_ChiToDuc': 'Chí hiếu, đạo làm người',
    'T_SuHySinh_KC': 'Sự hy sinh vì đất nước',
    'T_NguoiMe': 'Hình ảnh người mẹ',
}
