"""Display labels with Vietnamese diacritics for Toán 9 ontology."""

DISPLAY_LABELS = {
    # Definitions
    'D_CanBacHai': 'Căn bậc hai của số không âm',
    'D_CanBacHaiSoHoc': 'Căn bậc hai số học',
    'D_HamSoBacNhat': 'Hàm số bậc nhất y=ax+b',
    'D_HamSoBac2': 'Hàm số bậc hai y=ax² (a ≠ 0)',
    'D_HeSoGoc': 'Hệ số góc của đường thẳng',
    'D_PhuongTrinhBac2': 'Phương trình bậc hai một ẩn',
    'D_HePhuongTrinh': 'Hệ hai phương trình bậc nhất hai ẩn',
    'D_Parabol': 'Parabol y=ax²',
    'D_DuongTron': 'Đường tròn',
    'D_TiepTuyen': 'Tiếp tuyến của đường tròn',
    'D_CungTron': 'Cung tròn',
    'D_DayCung': 'Dây cung của đường tròn',
    'D_GocNoiTiep': 'Góc nội tiếp',
    'D_GocOTam': 'Góc ở tâm',
    'D_TuGiacNoiTiep': 'Tứ giác nội tiếp',
    'D_HinhTru': 'Hình trụ',
    'D_HinhNon': 'Hình nón',
    'D_HinhCau': 'Hình cầu',
    'D_CungChuong': 'Cung chứa góc',
    'D_Biet_PTB2': 'Biệt thức Δ của phương trình bậc 2',

    # Theorems
    'T_Pythagoras': 'Định lí Pythagoras (toán 8, nhắc lại)',
    'T_Thales': 'Định lí Ta-lét',
    'T_ThalesDaoNguoc': 'Định lí Ta-lét đảo',
    'T_VietaQuan': 'Định lí Vi-ét',
    'T_VietaDao': 'Định lí Vi-ét đảo',
    'T_TTHamSoBacNhat': 'Tính chất hàm số bậc nhất',
    'T_TTHamSoBac2': 'Tính chất hàm số bậc hai',
    'T_HeThucLuong': 'Hệ thức lượng trong tam giác vuông',
    'T_TTTiepTuyen': 'Tính chất hai tiếp tuyến cắt nhau',
    'T_LienHeCungVaDay': 'Liên hệ giữa cung và dây',
    'T_GocNoiTiep_TT': 'Định lí góc nội tiếp',
    'T_GocTaoBoiTTVaDay': 'Góc tạo bởi tia tiếp tuyến và dây cung',
    'T_GocCoDinhONgoaiHinhTron': 'Góc có đỉnh ngoài đường tròn',
    'T_TuGiacNoiTiepDK': 'Điều kiện tứ giác nội tiếp',
    'T_DuongTronNoiTiep': 'Định lí đường tròn nội/ngoại tiếp đa giác đều',
    'T_DiaLuongCan': 'Quy tắc nhân/chia căn bậc hai',
    'T_Lien_HamSo_Parabol': 'Vị trí tương đối đường thẳng – parabol',
    'T_DK_PTB2_CoNghiem': 'Điều kiện có nghiệm của phương trình bậc 2 (Δ ≥ 0)',

    # Formulas
    'F_Delta': 'Công thức Δ = b² − 4ac',
    'F_NghiemPTB2': 'Công thức nghiệm x = (−b ± √Δ) / 2a',
    'F_VietaTong': 'Tổng nghiệm S = −b/a (Vi-ét)',
    'F_VietaTich': 'Tích nghiệm P = c/a (Vi-ét)',
    'F_DoDaiCung': 'Độ dài cung l = πRn/180',
    'F_DienTichHinhQuat': 'Diện tích hình quạt S = πR²n/360',
    'F_ChuViDuongTron': 'Chu vi đường tròn C = 2πR',
    'F_DienTichHinhTron': 'Diện tích hình tròn S = πR²',
    'F_DTXQHinhTru': 'Diện tích xung quanh hình trụ S_xq = 2πRh',
    'F_TheTichHinhTru': 'Thể tích hình trụ V = πR²h',
    'F_DTXQHinhNon': 'Diện tích xung quanh hình nón S_xq = πRl',
    'F_TheTichHinhNon': 'Thể tích hình nón V = (1/3)πR²h',
    'F_DienTichHinhCau': 'Diện tích mặt cầu S = 4πR²',
    'F_TheTichHinhCau': 'Thể tích hình cầu V = (4/3)πR³',
    'F_HSL_BinhPhuong_TGV': 'Hệ thức b² = a·b\', c² = a·c\' (HSL trong TGV)',
    'F_HSL_DuongCao_TGV': 'Hệ thức h² = b\'·c\' (HSL trong TGV)',
    'F_HamSoBacNhat': 'y = ax + b',
    'F_HamSoBac2_DonGian': 'y = ax²',
    'F_KhoangCach2Diem': 'Khoảng cách 2 điểm d = √((x₁−x₂)² + (y₁−y₂)²)',

    # Concepts
    'C_SoThuc': 'Số thực',
    'C_SoVoTi': 'Số vô tỉ',
    'C_HamSo': 'Hàm số',
    'C_DoThiHamSo': 'Đồ thị hàm số',
    'C_HamSoDongBien': 'Hàm số đồng biến',
    'C_HamSoNghichBien': 'Hàm số nghịch biến',
    'C_HeTrucToaDo': 'Hệ trục tọa độ Oxy',
    'C_NghiemPT': 'Nghiệm của phương trình',
    'C_DongQui': 'Ba đường thẳng đồng quy',
    'C_CanhGocQuanHe_TGV': 'Quan hệ cạnh – góc trong tam giác vuông',
    'C_DuongCao_TGV': 'Đường cao trong tam giác vuông',
    'C_VTDT_VoiDuongTron': 'Vị trí tương đối của đường thẳng và đường tròn',
    'C_VT2DuongTron': 'Vị trí tương đối của hai đường tròn',
    'C_DuongTronNoiTiep_DaGiac': 'Đường tròn nội/ngoại tiếp đa giác',
    'C_TamGiacNoiTiep': 'Tam giác nội tiếp đường tròn',
    'C_DaGiacDeu': 'Đa giác đều',
    'C_HinhLangTru': 'Hình lăng trụ đứng (nhắc lại)',
    'C_ThetichKhoi_TronXoay': 'Thể tích khối tròn xoay',

    # Methods
    'M_KhaiCan': 'Khai phương tích, thương',
    'M_TrucCanMau': 'Trục căn thức ở mẫu',
    'M_HeThePPThe': 'Phương pháp thế (giải hệ PT)',
    'M_HeThePPCong': 'Phương pháp cộng đại số (giải hệ PT)',
    'M_DatAnPhu': 'Đặt ẩn phụ',
    'M_VietaNhamNghiem': 'Nhẩm nghiệm bằng Vi-ét',
    'M_VeDoThiParabol': 'Vẽ đồ thị parabol',
    'M_VeDoThiDTB1': 'Vẽ đồ thị hàm số bậc nhất',
    'M_TimDieuKienDinhTH': 'Tìm điều kiện có nghiệm / nghiệm chung',
    'M_ChungMinhTiepTuyen': 'Chứng minh đường thẳng là tiếp tuyến',
    'M_ChungMinhTuGiacNoiTiep': 'Chứng minh tứ giác nội tiếp',
    'M_ChungMinhDongQui': 'Chứng minh 3 điểm thẳng hàng / 3 đường đồng quy',
    'M_TinhGoc_DuongTron': 'Tính góc liên quan đường tròn',
    'M_TinhDienTich_HinhKhongGian': 'Tính diện tích / thể tích hình không gian',
    'M_GiaiToanThucTe': 'Giải bài toán thực tế bằng PT / HPT',

    # Problem types
    'PT_RutGonBieuThucCan': 'Rút gọn biểu thức chứa căn',
    'PT_GiaiPTVoCan': 'Giải phương trình vô tỉ (có căn)',
    'PT_GiaiHPTBac1_2An': 'Giải hệ phương trình bậc nhất 2 ẩn',
    'PT_GiaiPTBac2': 'Giải phương trình bậc 2',
    'PT_TrungGianQuaPhuongTrinhBac2': 'Đưa về PT bậc 2 (trung gian)',
    'PT_BieuDienDoThi': 'Vẽ đồ thị và xác định vị trí tương đối',
    'PT_TimCucTriBang_BieuThuc': 'Tìm GTLN – GTNN của biểu thức',
    'PT_DinhLyHamSoBacNhat': 'Bài toán về hàm số bậc nhất',
    'PT_DinhLyHamSoBac2': 'Bài toán về hàm số bậc hai và parabol',
    'PT_DinhLyTimThamSo': 'Tìm tham số để PT thoả điều kiện',
    'PT_BaiToanThucTe': 'Giải bài toán bằng cách lập PT / HPT',
    'PT_ChungMinhHinhHoc_DuongTron': 'Chứng minh hình học liên quan đường tròn',
    'PT_TinhGoc_TamGiac_DuongTron': 'Tính góc / độ dài trong tam giác và đường tròn',
    'PT_TinhHinhKhongGian': 'Tính đại lượng hình trụ, nón, cầu',
    'PT_ChungMinh_TQNoi': 'Chứng minh tứ giác nội tiếp đường tròn',

    # Objects
    'O_TamGiacVuong': 'Tam giác vuông',
    'O_DuongTron_DT': 'Đường tròn cụ thể',
    'O_HinhTron': 'Hình tròn',
    'O_DuongThang_2D': 'Đường thẳng trong mặt phẳng',
    'O_Parabol_DT': 'Parabol cụ thể',
    'O_TuGiac': 'Tứ giác',
    'O_HinhTru_DT': 'Hình trụ cụ thể',
    'O_HinhNon_DT': 'Hình nón cụ thể',
    'O_HinhCau_DT': 'Hình cầu cụ thể',
    'O_BieuThucCan': 'Biểu thức chứa căn',
}
