"""Display labels with Vietnamese diacritics for Lý 9 ontology."""

DISPLAY_LABELS = {
    # Laws
    'L_Ohm': 'Định luật Ôm (Ohm)',
    'L_JunLenxo': 'Định luật Jun – Len-xơ',
    'L_BaoToanNL': 'Định luật bảo toàn và chuyển hóa năng lượng',
    'L_KhucXaAnhSang': 'Định luật khúc xạ ánh sáng',
    'L_CamUngDienTu': 'Hiện tượng cảm ứng điện từ (Faraday)',
    'L_NhiemTu': 'Quy tắc nhiễm từ của dòng điện (quy tắc bàn tay phải)',
    'L_BanTayTrai': 'Quy tắc bàn tay trái (xác định lực từ)',
    'L_TruyenThangAS': 'Định luật truyền thẳng ánh sáng (ôn tập)',
    'L_PhanXaAS': 'Định luật phản xạ ánh sáng (ôn tập)',
    'L_MayBienThe': 'Công thức máy biến thế U₁/U₂ = N₁/N₂',

    # Formulas
    'F_Ohm': 'U = I · R (định luật Ôm)',
    'F_R_U_I': 'R = U / I',
    'F_NoiTiep_R': 'R_tđ = R₁ + R₂ (mạch nối tiếp)',
    'F_SongSong_R': '1/R_tđ = 1/R₁ + 1/R₂ (mạch song song)',
    'F_NoiTiep_U': 'U = U₁ + U₂ (mạch nối tiếp)',
    'F_NoiTiep_I': 'I = I₁ = I₂ (mạch nối tiếp)',
    'F_SongSong_U': 'U = U₁ = U₂ (mạch song song)',
    'F_SongSong_I': 'I = I₁ + I₂ (mạch song song)',
    'F_R_DayDan': 'R = ρ · L / S (điện trở dây dẫn)',
    'F_CongSuat': 'P = U · I (công suất điện)',
    'F_CongSuat_2': 'P = I² · R = U² / R',
    'F_DienNang': 'A = P · t = U · I · t (điện năng)',
    'F_JunLenxo': 'Q = I² · R · t (nhiệt lượng toả ra — Jun-Len-xơ)',
    'F_MayBT': 'U₁/U₂ = N₁/N₂ (máy biến thế)',
    'F_ThauKinh_HoiTu': '1/f = 1/d + 1/d\' (thấu kính hội tụ)',
    'F_DoBoi_AnhThau': 'h\'/h = d\'/d (độ phóng đại của ảnh)',
    'F_KhucXa_Sin': 'Quan hệ góc tới – góc khúc xạ (định tính)',

    # Quantities
    'Q_CuongDoDongDien': 'Cường độ dòng điện (I)',
    'Q_HieuDienThe': 'Hiệu điện thế (U)',
    'Q_DienTro': 'Điện trở (R)',
    'Q_DienTroSuat': 'Điện trở suất (ρ)',
    'Q_CongSuatDien': 'Công suất điện (P)',
    'Q_DienNang': 'Điện năng / công của dòng điện (A)',
    'Q_NhietLuong': 'Nhiệt lượng (Q)',
    'Q_ChieuDaiDay': 'Chiều dài dây dẫn (L)',
    'Q_TietDienDay': 'Tiết diện dây (S)',
    'Q_ThoiGian': 'Thời gian (t)',
    'Q_TieuCu': 'Tiêu cự (f)',
    'Q_KhoangCachVat': 'Khoảng cách từ vật đến thấu kính (d)',
    'Q_KhoangCachAnh': "Khoảng cách từ ảnh đến thấu kính (d')",
    'Q_SoVongDay': 'Số vòng dây cuộn sơ cấp / thứ cấp (N)',
    'Q_NhietDung': 'Nhiệt dung riêng (c)',

    # Units
    'U_Ampe': 'Ampe (A)',
    'U_Von': 'Vôn (V)',
    'U_Ohm': 'Ôm (Ω)',
    'U_OhmMet': 'Ôm · mét (Ω · m)',
    'U_Oat': 'Oát (W)',
    'U_Jun': 'Jun (J)',
    'U_KilowattGio': 'Kilôwatt giờ (kWh)',
    'U_Met': 'Mét (m)',
    'U_MetVuong': 'Mét vuông (m²)',
    'U_Giay': 'Giây (s)',
    'U_JouleKgK': 'J/(kg · K)',

    # Phenomena
    'PH_KhucXa': 'Khúc xạ ánh sáng',
    'PH_PhanXa': 'Phản xạ ánh sáng (ôn tập)',
    'PH_TanSac': 'Tán sắc ánh sáng',
    'PH_TrongThay': 'Trông thấy ảnh của vật qua thấu kính',
    'PH_CamUngDienTu_PH': 'Cảm ứng điện từ',
    'PH_TuTruongCuaDongDien': 'Từ trường của dòng điện',
    'PH_TacDungTuCuaDongDien': 'Tác dụng từ của dòng điện',
    'PH_LucDienTu': 'Lực điện từ tác dụng lên dây dẫn có dòng điện',
    'PH_TruyenTaiDienNang': 'Hao phí khi truyền tải điện năng đi xa',
    'PH_DoanMachHoTai': 'Đoản mạch / quá tải',
    'PH_MatCan_MatLao': 'Mắt cận, mắt lão (tật của mắt)',
    'PH_AnhSangMau': 'Tổng hợp và phân tích ánh sáng màu',
    'PH_TacDungNhietAS': 'Tác dụng nhiệt, quang, sinh học của ánh sáng',

    # Devices
    'DV_AmpeKe': 'Ampe kế',
    'DV_VonKe': 'Vôn kế',
    'DV_DienTro': 'Điện trở',
    'DV_BienTro': 'Biến trở (con chạy)',
    'DV_BongDen': 'Bóng đèn dây tóc',
    'DV_Pin': 'Pin / nguồn điện',
    'DV_ThauKinhHT': 'Thấu kính hội tụ',
    'DV_ThauKinhPK': 'Thấu kính phân kì',
    'DV_GuongPhang': 'Gương phẳng (ôn tập)',
    'DV_MayAnh': 'Máy ảnh',
    'DV_KinhLup': 'Kính lúp',
    'DV_NamCham': 'Nam châm',
    'DV_DongCoDien1C': 'Động cơ điện một chiều',
    'DV_MayPhatDien': 'Máy phát điện xoay chiều',
    'DV_MayBienThe': 'Máy biến thế (máy biến áp)',
    'DV_DongHoDoDien': 'Đồng hồ đo điện (công tơ)',
    'DV_LangKinh': 'Lăng kính (tán sắc)',
    'DV_MatNguoi': 'Mắt người (cấu tạo quang học)',

    # Concepts
    'C_MachNoiTiep': 'Đoạn mạch nối tiếp',
    'C_MachSongSong': 'Đoạn mạch song song',
    'C_MachHonHop': 'Đoạn mạch hỗn hợp',
    'C_TuTruong': 'Từ trường',
    'C_DuongSucTu': 'Đường sức từ',
    'C_TuPhoDongDien': 'Từ phổ của dòng điện',
    'C_NhiemTu_KL': 'Sự nhiễm từ của kim loại (sắt, thép)',
    'C_DongDienXoayChieu': 'Dòng điện xoay chiều',
    'C_TieuDiem': 'Tiêu điểm của thấu kính',
    'C_TrucChinh': 'Trục chính của thấu kính',
    'C_AnhThat': 'Ảnh thật (qua thấu kính)',
    'C_AnhAo': 'Ảnh ảo (qua thấu kính)',
    'C_CauToaAS': 'Cấu tạo ánh sáng trắng',
    'C_NangLuong': 'Năng lượng và các dạng năng lượng',
    'C_ChuyenHoaNL': 'Sự chuyển hóa năng lượng',
    'C_CongDongDien_KN': 'Công của dòng điện (điện năng tiêu thụ)',
    'C_AnToanDien': 'An toàn khi sử dụng điện',
    'C_TietKiemDienNang': 'Tiết kiệm điện năng',

    # Methods
    'M_GiaiMachNoiTiep': 'Giải mạch nối tiếp (tính I, U, R)',
    'M_GiaiMachSongSong': 'Giải mạch song song',
    'M_GiaiMachHonHop': 'Giải mạch hỗn hợp',
    'M_TinhDienNang_CSuat': 'Tính điện năng và công suất tiêu thụ',
    'M_TinhQ_JunLenxo': 'Tính nhiệt lượng toả ra theo Jun-Len-xơ',
    'M_QuyTacBanTayPhai': 'Xác định chiều đường sức từ (quy tắc bàn tay phải)',
    'M_QuyTacBanTayTrai': 'Xác định chiều lực từ (bàn tay trái)',
    'M_VeAnhQuaTKHT': 'Vẽ ảnh của vật qua thấu kính hội tụ',
    'M_VeAnhQuaTKPK': 'Vẽ ảnh của vật qua thấu kính phân kì',
    'M_TinhAnhBangCongThuc': 'Tính vị trí và độ cao ảnh bằng công thức',
    'M_TinhMayBienThe': 'Tính toán với máy biến thế',

    # Problem types
    'PT_TinhR_Ohm': 'Tính điện trở từ U, I (định luật Ôm)',
    'PT_TinhU_TuongDuong': 'Tính điện trở tương đương của mạch',
    'PT_MachHonHop_IUR': 'Phân tích mạch hỗn hợp tìm I, U, R',
    'PT_TinhCongSuat': 'Tính công suất thiết bị điện',
    'PT_TinhDienNangTieuThu': 'Tính điện năng tiêu thụ trong thời gian t',
    'PT_NhietLuongJun': 'Tính nhiệt lượng toả ra (Jun-Len-xơ)',
    'PT_XacDinhChieuLuc_BTT': 'Xác định chiều lực từ bằng bàn tay trái',
    'PT_ChieuDongDienCamUng': 'Xác định chiều dòng điện cảm ứng',
    'PT_VeAnhQuaTK': 'Vẽ ảnh của vật qua thấu kính',
    'PT_TinhViTriAnh': 'Tính vị trí và độ cao ảnh',
    'PT_MayBienThe_UN': 'Tính toán máy biến thế (U, N)',
    'PT_HaoPhiTTDN': 'Tính hao phí trên đường dây truyền tải',

    # Experiments
    'E_DoDinhLuatOhm': 'Đo sự phụ thuộc I vào U (kiểm chứng Ohm)',
    'E_DoRDayDan': 'Đo điện trở dây dẫn theo L, S, vật liệu',
    'E_JunLenxo': 'Kiểm chứng định luật Jun-Len-xơ',
    'E_TuPho': 'Quan sát từ phổ nam châm và dòng điện',
    'E_CamUng': 'Phát hiện hiện tượng cảm ứng điện từ',
    'E_ThauKinh': 'Khảo sát ảnh qua thấu kính',
    'E_TanSacAS': 'Kiểm chứng sự tán sắc ánh sáng bằng lăng kính',
}
