"""Display labels with Vietnamese diacritics for Hóa 9 ontology."""

DISPLAY_LABELS = {
    # Substance Classes
    'SC_Oxit': 'Oxit',
    'SC_OxitAxit': 'Oxit axit',
    'SC_OxitBazo': 'Oxit bazơ',
    'SC_OxitLuongTinh': 'Oxit lưỡng tính',
    'SC_OxitTrungTinh': 'Oxit trung tính',
    'SC_Axit': 'Axit',
    'SC_AxitManh': 'Axit mạnh',
    'SC_AxitYeu': 'Axit yếu',
    'SC_Bazo': 'Bazơ',
    'SC_BazoTan': 'Bazơ tan (kiềm)',
    'SC_BazoKhongTan': 'Bazơ không tan',
    'SC_Muoi': 'Muối',
    'SC_MuoiAxit': 'Muối axit',
    'SC_MuoiTrungHoa': 'Muối trung hòa',
    'SC_KimLoai': 'Kim loại',
    'SC_KimLoaiKiem': 'Kim loại kiềm',
    'SC_KimLoaiKiemTho': 'Kim loại kiềm thổ',
    'SC_PhiKim': 'Phi kim',
    'SC_Hidrocacbon': 'Hiđrocacbon',
    'SC_HCNoi': 'Hiđrocacbon no (ankan)',
    'SC_HCKhong': 'Hiđrocacbon không no',
    'SC_HCThom': 'Hiđrocacbon thơm (aren)',
    'SC_Ancol': 'Ancol (rượu)',
    'SC_Axit_HC': 'Axit hữu cơ (axit cacboxylic)',
    'SC_Este': 'Este',
    'SC_Gluxit': 'Gluxit (cacbohiđrat)',
    'SC_Polime': 'Polime',

    # Substances
    'S_CaO': 'Canxi oxit CaO (vôi sống)',
    'S_SO2': 'Lưu huỳnh đioxit SO₂ (khí sunfurơ)',
    'S_SO3': 'Lưu huỳnh trioxit SO₃',
    'S_CO2': 'Cacbon đioxit CO₂ (khí cacbonic)',
    'S_CO': 'Cacbon monoxit CO',
    'S_P2O5': 'Điphotpho pentaoxit P₂O₅',
    'S_Al2O3': 'Nhôm oxit Al₂O₃',
    'S_Fe2O3': 'Sắt(III) oxit Fe₂O₃',
    'S_CuO': 'Đồng(II) oxit CuO',
    'S_Na2O': 'Natri oxit Na₂O',
    'S_HCl': 'Axit clohiđric HCl',
    'S_H2SO4': 'Axit sunfuric H₂SO₄',
    'S_HNO3': 'Axit nitric HNO₃',
    'S_H2CO3': 'Axit cacbonic H₂CO₃',
    'S_H3PO4': 'Axit photphoric H₃PO₄',
    'S_H2SO3': 'Axit sunfurơ H₂SO₃',
    'S_CH3COOH': 'Axit axetic CH₃COOH (giấm)',
    'S_NaOH': 'Natri hiđroxit NaOH (xút)',
    'S_KOH': 'Kali hiđroxit KOH',
    'S_CaOH2': 'Canxi hiđroxit Ca(OH)₂ (vôi tôi)',
    'S_BaOH2': 'Bari hiđroxit Ba(OH)₂',
    'S_CuOH2': 'Đồng(II) hiđroxit Cu(OH)₂',
    'S_FeOH3': 'Sắt(III) hiđroxit Fe(OH)₃',
    'S_AlOH3': 'Nhôm hiđroxit Al(OH)₃',
    'S_NaCl': 'Natri clorua NaCl (muối ăn)',
    'S_CaCO3': 'Canxi cacbonat CaCO₃ (đá vôi)',
    'S_NaHCO3': 'Natri hiđrocacbonat NaHCO₃ (thuốc muối)',
    'S_Na2CO3': 'Natri cacbonat Na₂CO₃ (soda)',
    'S_CuSO4': 'Đồng(II) sunfat CuSO₄',
    'S_FeCl3': 'Sắt(III) clorua FeCl₃',
    'S_BaSO4': 'Bari sunfat BaSO₄',
    'S_Na': 'Natri Na',
    'S_K': 'Kali K',
    'S_Ca': 'Canxi Ca',
    'S_Mg': 'Magie Mg',
    'S_Al': 'Nhôm Al',
    'S_Fe': 'Sắt Fe',
    'S_Cu': 'Đồng Cu',
    'S_Zn': 'Kẽm Zn',
    'S_Ag': 'Bạc Ag',
    'S_Au': 'Vàng Au',
    'S_Cl2': 'Clo Cl₂',
    'S_O2': 'Oxi O₂',
    'S_H2': 'Hiđro H₂',
    'S_N2': 'Nitơ N₂',
    'S_C_element': 'Cacbon C',
    'S_S_element': 'Lưu huỳnh S',
    'S_CH4': 'Metan CH₄ (khí bùn)',
    'S_C2H4': 'Etilen C₂H₄',
    'S_C2H2': 'Axetilen C₂H₂',
    'S_C6H6': 'Benzen C₆H₆',
    'S_C2H5OH': 'Rượu etylic (ancol etylic) C₂H₅OH',
    'S_CH3OH': 'Metanol CH₃OH',
    'S_EsteC2H5': 'Etyl axetat CH₃COOC₂H₅',
    'S_Glucose': 'Glucozơ C₆H₁₂O₆',
    'S_Saccarose': 'Saccarozơ C₁₂H₂₂O₁₁',
    'S_TinhBot': 'Tinh bột (C₆H₁₀O₅)ₙ',
    'S_Xenluloz': 'Xenlulozơ (C₆H₁₀O₅)ₙ',
    'S_Poli_Ethylene': 'Polietilen (PE)',
    'S_Poli_VinylClorua': 'Polivinyl clorua (PVC)',
    'S_H2O': 'Nước H₂O',

    # Reaction Types
    'RT_TrungHoa': 'Phản ứng trung hòa',
    'RT_PhanHuy': 'Phản ứng phân hủy',
    'RT_HoaHop': 'Phản ứng hóa hợp',
    'RT_The': 'Phản ứng thế',
    'RT_TraoDoi': 'Phản ứng trao đổi',
    'RT_OXK': 'Phản ứng oxi hóa – khử',
    'RT_Cong': 'Phản ứng cộng',
    'RT_TrungHop': 'Phản ứng trùng hợp',
    'RT_ThuyPhan': 'Phản ứng thủy phân',
    'RT_Este_Hoa': 'Phản ứng este hóa',
    'RT_LenMen': 'Phản ứng lên men',
    'RT_Chay': 'Phản ứng cháy (đốt cháy)',

    # Properties
    'P_TanTrongNuoc': 'Tan trong nước',
    'P_PhanUngVoiAxit': 'Phản ứng với axit',
    'P_PhanUngVoiBazo': 'Phản ứng với bazơ',
    'P_PhanUngVoiOxi': 'Phản ứng với oxi (cháy)',
    'P_PhanUngVoiNuoc': 'Phản ứng với nước',
    'P_PhanUngVoiKimLoai': 'Phản ứng với kim loại',
    'P_LamDoiMauQT': 'Làm đổi màu quỳ tím',
    'P_DoiMauPhenolphthalein': 'Làm đổi màu phenolphtalein',
    'P_TacDungVoiPhiKim': 'Tác dụng với phi kim',
    'P_DienPhanDuocDDND': 'Điện phân được dung dịch',

    # Functional groups
    'FG_OH': 'Nhóm hiđroxyl –OH',
    'FG_COOH': 'Nhóm cacboxyl –COOH',
    'FG_Este_Link': 'Liên kết este –COO–',
    'FG_DoiLK': 'Liên kết đôi C=C',
    'FG_BaLK': 'Liên kết ba C≡C',
    'FG_Vong6': 'Vòng benzen',

    # Concepts
    'C_HoaTri': 'Hóa trị',
    'C_PTHH': 'Phương trình hóa học (PTHH)',
    'C_CanBangPTHH': 'Cân bằng phương trình hóa học',
    'C_BangTuanHoan': 'Bảng tuần hoàn các nguyên tố hóa học',
    'C_ChuKi': 'Chu kì (trong BTH)',
    'C_NhomA': 'Nhóm A trong BTH',
    'C_DinhLuatTuanHoan': 'Định luật tuần hoàn',
    'C_DayHoatDongKimLoai': 'Dãy hoạt động hóa học của kim loại',
    'C_DieuChe_KL_1': 'Điều chế kim loại (luyện kim)',
    'C_pH': 'Độ pH của dung dịch',
    'C_MolKhoiLuong': 'Mol và khối lượng mol',
    'C_NongDoDungDich': 'Nồng độ dung dịch (C%, Cₘ)',
    'C_SuChuyenHoa_DongDang': 'Sự chuyển hóa các chất hữu cơ',
    'C_DongPhan': 'Đồng phân',

    # Processes
    'PR_DienPhanNaCl': 'Điện phân dung dịch NaCl bão hòa (sản xuất NaOH)',
    'PR_LuyenGang': 'Luyện gang trong lò cao',
    'PR_LuyenThep': 'Luyện thép từ gang',
    'PR_SanXuat_H2SO4': 'Sản xuất H₂SO₄ công nghiệp',
    'PR_SanXuat_NH3': 'Sản xuất NH₃ (tổng hợp Haber)',
    'PR_LenMenRuou': 'Lên men rượu etylic từ tinh bột',
    'PR_LenMenGiam': 'Lên men giấm từ rượu',
    'PR_SanXuat_Voi': 'Nung vôi (sản xuất vôi sống)',
    'PR_SanXuatXiMang': 'Sản xuất xi măng',
    'PR_SanXuatThuyTinh': 'Sản xuất thủy tinh',

    # Reactions (full labels with diacritics + proper subscripts)
    'R_NaOH_HCl': 'NaOH + HCl → NaCl + H₂O',
    'R_CaO_H2O': 'CaO + H₂O → Ca(OH)₂',
    'R_CO2_CaOH2': 'CO₂ + Ca(OH)₂ → CaCO₃ + H₂O (CO₂ làm đục nước vôi)',
    'R_CaCO3_Nhiet': 'CaCO₃ ⟶(t°) CaO + CO₂ (nung đá vôi)',
    'R_Zn_HCl': 'Zn + 2HCl → ZnCl₂ + H₂',
    'R_Fe_CuSO4': 'Fe + CuSO₄ → FeSO₄ + Cu (sắt đẩy đồng)',
    'R_Fe_HCl': 'Fe + 2HCl → FeCl₂ + H₂',
    'R_Cu_H2SO4dac': 'Cu + 2H₂SO₄(đặc) ⟶(t°) CuSO₄ + SO₂ + 2H₂O',
    'R_Al_NaOH': '2Al + 2NaOH + 2H₂O → 2NaAlO₂ + 3H₂',
    'R_CH4_Cl2': 'CH₄ + Cl₂ ⟶(as) CH₃Cl + HCl',
    'R_C2H4_Br2': 'C₂H₄ + Br₂ → C₂H₄Br₂ (etilen làm mất màu brom)',
    'R_C2H2_H2': 'C₂H₂ + 2H₂ ⟶(Ni) C₂H₆ (cộng hiđro)',
    'R_C2H5OH_Na': '2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂',
    'R_CH3COOH_NaOH': 'CH₃COOH + NaOH → CH₃COONa + H₂O',
    'R_CH3COOH_C2H5OH': 'CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O (este hóa)',
    'R_Glucose_Fermentation': 'C₆H₁₂O₆ ⟶(men) 2C₂H₅OH + 2CO₂ (lên men rượu)',
    'R_C_O2': 'C + O₂ → CO₂',
    'R_H2_O2': '2H₂ + O₂ → 2H₂O',
    'R_SO2_O2_V2O5': '2SO₂ + O₂ ⟶(V₂O₅, t°) 2SO₃',
}
